// Code generated by protoc-gen-go. DO NOT EDIT.
// source: net/data/message/message.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	net/data/message/message.proto

It has these top-level messages:
	Message
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	ActorID            string               `protobuf:"bytes,1,opt,name=ActorID,json=actorID" json:"ActorID,omitempty"`
	IPAddress          string               `protobuf:"bytes,2,opt,name=IPAddress,json=iPAddress" json:"IPAddress,omitempty"`
	GoOS               string               `protobuf:"bytes,3,opt,name=GoOS,json=goOS" json:"GoOS,omitempty"`
	Kernel             string               `protobuf:"bytes,4,opt,name=Kernel,json=kernel" json:"Kernel,omitempty"`
	Core               string               `protobuf:"bytes,5,opt,name=Core,json=core" json:"Core,omitempty"`
	Platform           string               `protobuf:"bytes,6,opt,name=Platform,json=platform" json:"Platform,omitempty"`
	OS                 string               `protobuf:"bytes,7,opt,name=OS,json=oS" json:"OS,omitempty"`
	Hostname           string               `protobuf:"bytes,8,opt,name=Hostname,json=hostname" json:"Hostname,omitempty"`
	CPUs               int32                `protobuf:"varint,9,opt,name=CPUs,json=cPUs" json:"CPUs,omitempty"`
	CurrentInstruction *Message_Instruction `protobuf:"bytes,10,opt,name=CurrentInstruction,json=currentInstruction" json:"CurrentInstruction,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetActorID() string {
	if m != nil {
		return m.ActorID
	}
	return ""
}

func (m *Message) GetIPAddress() string {
	if m != nil {
		return m.IPAddress
	}
	return ""
}

func (m *Message) GetGoOS() string {
	if m != nil {
		return m.GoOS
	}
	return ""
}

func (m *Message) GetKernel() string {
	if m != nil {
		return m.Kernel
	}
	return ""
}

func (m *Message) GetCore() string {
	if m != nil {
		return m.Core
	}
	return ""
}

func (m *Message) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *Message) GetOS() string {
	if m != nil {
		return m.OS
	}
	return ""
}

func (m *Message) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Message) GetCPUs() int32 {
	if m != nil {
		return m.CPUs
	}
	return 0
}

func (m *Message) GetCurrentInstruction() *Message_Instruction {
	if m != nil {
		return m.CurrentInstruction
	}
	return nil
}

type Message_Instruction struct {
	ModuleName string `protobuf:"bytes,1,opt,name=ModuleName,json=moduleName" json:"ModuleName,omitempty"`
}

func (m *Message_Instruction) Reset()                    { *m = Message_Instruction{} }
func (m *Message_Instruction) String() string            { return proto.CompactTextString(m) }
func (*Message_Instruction) ProtoMessage()               {}
func (*Message_Instruction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Message_Instruction) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterType((*Message_Instruction)(nil), "message.Message.Instruction")
}

func init() { proto.RegisterFile("net/data/message/message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xdf, 0x6a, 0xbb, 0x30,
	0x14, 0xc7, 0xd1, 0x9f, 0xf5, 0xcf, 0x29, 0xfc, 0x2e, 0xce, 0xc5, 0x08, 0xa5, 0x14, 0xd9, 0x95,
	0x37, 0xb3, 0xb0, 0x3d, 0x41, 0xe9, 0x60, 0x93, 0xad, 0x53, 0x94, 0x3e, 0x40, 0xa6, 0x59, 0x57,
	0xa6, 0x39, 0x25, 0x89, 0x2f, 0xbb, 0xa7, 0x19, 0x46, 0x1d, 0x85, 0x5d, 0x25, 0x9f, 0xef, 0xf9,
	0x24, 0x1c, 0xbe, 0xb0, 0x91, 0xc2, 0x6c, 0x1b, 0x6e, 0xf8, 0xb6, 0x13, 0x5a, 0xf3, 0x93, 0x98,
	0xcf, 0xf4, 0xa2, 0xc8, 0x10, 0x06, 0x13, 0xde, 0x7e, 0xbb, 0x10, 0x1c, 0xc6, 0x3b, 0x32, 0x08,
	0x76, 0xb5, 0x21, 0x95, 0x3d, 0x32, 0x27, 0x76, 0x92, 0xa8, 0x0c, 0xf8, 0x88, 0xb8, 0x86, 0x28,
	0x2b, 0x76, 0x4d, 0xa3, 0x84, 0xd6, 0xcc, 0xb5, 0xb3, 0xe8, 0x3c, 0x07, 0x88, 0xe0, 0x3d, 0x51,
	0x5e, 0xb1, 0x7f, 0x76, 0xe0, 0x9d, 0x28, 0xaf, 0xf0, 0x06, 0xfc, 0x17, 0xa1, 0xa4, 0x68, 0x99,
	0x67, 0x53, 0xff, 0xcb, 0xd2, 0xe0, 0xee, 0x49, 0x09, 0xb6, 0x18, 0xdd, 0x9a, 0x94, 0xc0, 0x15,
	0x84, 0x45, 0xcb, 0xcd, 0x07, 0xa9, 0x8e, 0xf9, 0x36, 0x0f, 0x2f, 0x13, 0xe3, 0x7f, 0x70, 0xf3,
	0x8a, 0x05, 0x36, 0x75, 0xa9, 0x1a, 0xdc, 0x67, 0xd2, 0x46, 0xf2, 0x4e, 0xb0, 0x70, 0x74, 0x3f,
	0x27, 0xb6, 0x7f, 0x17, 0x47, 0xcd, 0xa2, 0xd8, 0x49, 0x16, 0xa5, 0x57, 0x17, 0x47, 0x8d, 0xaf,
	0x80, 0xfb, 0x5e, 0x29, 0x21, 0x4d, 0x26, 0xb5, 0x51, 0x7d, 0x6d, 0xce, 0x24, 0x19, 0xc4, 0x4e,
	0xb2, 0xbc, 0x5f, 0xa7, 0x73, 0x29, 0x53, 0x03, 0xe9, 0x95, 0x53, 0x62, 0xfd, 0xe7, 0xdd, 0xea,
	0x0e, 0x96, 0x57, 0x88, 0x1b, 0x80, 0x03, 0x35, 0x7d, 0x2b, 0xde, 0x86, 0x75, 0xc6, 0xce, 0xa0,
	0xfb, 0x4d, 0xde, 0x7d, 0x5b, 0xf6, 0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0x4d, 0x8b,
	0xee, 0x8e, 0x01, 0x00, 0x00,
}
